# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-21 20:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import hs_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0045_auto_20190617_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/django_irods/download/', location='/hydroshare/hydroshare/bagsdata'), upload_to=hs_core.models.get_path),
        ),
    ]
