# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_irods.storage
import hs_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_core', '0046_auto_20190621_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=hs_core.models.get_path),
        ),
    ]
