### Local Configuration Variables ###
HS_PATH: /Users/danielsikes/Projects/commonsshare
HOST_SSL_DIR: /home/hydro/hs-certs
HS_DATABASE: pg.development.sql
HS_LOG_FILES: /Users/danielsikes/Projects/commonsshare/log
HS_SERVICE_UID: 1000
HS_SERVICE_GID: 1000

### Deployment Options ###
USE_NGINX: false
USE_SSL: false
USE_SECURITY: false
USE_HTTP_AUTH: false

### nginx Configuration Variables ###
FQDN_OR_IP: 152.54.6.164
NGINX_DIR: /Users/danielsikes/Projects/commonsshare/nginx

### SSL Configuration Variables ###
SSL_CERT_DIR: /Users/danielsikes/Projects/commonsshare/nginx/cert-files
SSL_CERT_FILE: hydrodev-vb.example.org.cert
SSL_KEY_FILE: hydrodev-vb.example.org.key

### REQUIRES BLANK LINE AFTER LAST VARIABLE DEFINITION ###
